frr defaults traditional
hostname ec2-a
log syslog informational
service integrated-vtysh-config

!
! BGP (Active)
!
router bgp 65000
 bgp router-id 169.254.208.49
 no bgp ebgp-requires-policy

 ! --- Tunnel2 (xfrm102) ---
 neighbor 169.254.125.246 remote-as 64512
 neighbor 169.254.125.246 update-source 169.254.125.245
 neighbor 169.254.125.246 timers 10 30

 ! --- Tunnel1 (xfrm101) ---
 neighbor 169.254.208.50 remote-as 64512
 neighbor 169.254.208.50 update-source 169.254.208.49
 neighbor 169.254.208.50 timers 10 30

 address-family ipv4 unicast
  ! ★広告するプレフィックス（Activeのみ）
  network 172.16.0.0/16
 exit-address-family
!
line vty