frr defaults traditional
hostname ec2-b
log syslog informational
service integrated-vtysh-config

!
! 広告ブロック用 route-map（全部deny）
!
route-map RM-OUT-BLOCK deny 10

!
! BGP (Standby)
!
router bgp 65000
 bgp router-id 169.254.208.49
 no bgp ebgp-requires-policy

 ! --- Tunnel2 (xfrm102) ---
 neighbor 169.254.125.246 remote-as 64512
 neighbor 169.254.125.246 update-source 169.254.125.245
 neighbor 169.254.125.246 timers 10 30

 ! --- Tunnel1 (xfrm101) ---
 neighbor 169.254.208.50 remote-as 64512
 neighbor 169.254.208.50 update-source 169.254.208.49
 neighbor 169.254.208.50 timers 10 30

 address-family ipv4 unicast
  ! network行は残してもOK（※outで落とすので広告されない）
  network 172.16.0.0/16

  ! ★Standbyは広告しない（outで全deny）
  neighbor 169.254.125.246 route-map RM-OUT-BLOCK out
  neighbor 169.254.208.50  route-map RM-OUT-BLOCK out
 exit-address-family
!
line vty